#!/bin/bash

set -e

# Colors
GREEN="\e[32m"
DEFAULT="\e[0m"
RED="\e[31m"

echo -e "${RED}This needs to be sourced${DEFAULT}"

if [[ -z ${AWS_SECRET_ACCESS_KEY} ]]; then
  echo -e "${RED}AWS values not found.${DEFAULT}"
  exit 1
else
  echo -e "${GREEN}Unsetting AWS Variables...${DEFAULT}"
  for key in $(env | grep AWS_ | cut -d= -f1);
    do unset $key;
  done
  echo -e "${GREEN}Done.${DEFAULT}"
fi
