FROM golang:tip-alpine3.23 AS builder

COPY . /tools/
WORKDIR /tools
RUN go build -o tools.dev .

FROM debian:trixie-slim

ARG NIX_VERBOSE
ENV NIX_VERBOSE=$NIX_VERBOSE
COPY --from=builder /tools/tools.dev /tools/tools.dev

RUN useradd -m testuser
RUN echo "testuser:p" | chpasswd

WORKDIR /tools
