FROM golang:trixie AS builder

COPY . /tools/
WORKDIR /tools
RUN go build -o tools.dev .

FROM debian:latest

COPY --from=builder /tools/internal/templates/bashrc.template /tools/internal/templates/
COPY --from=builder /tools/tools.dev /tools/tools.dev

RUN useradd -m testuser

WORKDIR /tools
USER testuser
