FROM golang:trixie AS builder

COPY . /tools/
WORKDIR /tools
RUN go build -o tools.dev .

FROM fedora:latest

COPY --from=builder /tools/tools.dev /tools/tools.dev

RUN useradd -m testuser
RUN usermod -aG wheel testuser
RUN echo "testuser:p" | chpasswd

WORKDIR /tools
USER testuser
